### ISSUE TITLE
Certain filters broken in v1.10-1 but working on v1.10.4-debian-1.0

### ISSUE THREAD

**Issue by trallnag** [fluent/fluentd-docker-image#221]
The issue: Some filter functions like adding a new key are broken in the Fluentd image based on Alpine. It works with Debian. It doesn't matter if I am using the built-in transformer or record modifier plugin.

Here is a `fluent.conf` to reproduce the issue. The new key `testkk` as well as `service` will not appear.

```
<source>
  @type  forward
  @id    input1
  port  24224
</source>

<filter docker.**>
  @type record_transformer

  remove_keys container_id,container_name
</filter>

<filter docker.**>
  @type record_transformer

  <record>
    testkk XXXXXXXXXXXXXXx
    service ${record["com.docker.swarm.service.name"]}
  </record>
</filter>

<match docker.**>
  @type file
  @id   output_docker1

  path         /fluentd/log/docker.*.log
  symlink_path /fluentd/log/docker.log
  append       true
  time_slice_format %Y%m%d
  time_slice_wait   1m
  time_format       %Y%m%dT%H%M%S%z
</match>
```

My docker compose to test it:

```
version: "3.8"

x-function: &defaults
  labels:
    ci-commit-tag: "1.0.0" #"${CI_COMMIT_TAG}"
    ci-project-url: fefefefefefe #"${CI_PROJECT_URL}"
  logging:
    driver: "fluentd"
    options:
      fluentd-async-connect: "true"
      tag: "docker.{{.ID}}"
      labels: 
        com.docker.swarm.service.name,com.docker.stack.namespace,com.docker.ucp.access.label,ci-commit-tag,ci-project-url

networks:
  mynetwork:

  logger:
    <<: *defaults
    image: chentex/random-logger:latest
    networks:
      - mynetwork
    
  fluentd:
    image: fluent/fluentd:v1.10-1
    networks:
      - mynetwork
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    volumes:
      - "/path/to/config/dir:/fluentd/etc"
```
